### ISSUE TITLE
Bring all tables to the same size

### ISSUE THREAD

**Issue by TheZoker** [Koenkk/zigbee2mqtt.io#22]
Hi Koenkk,

Amazing project!

I would like to add some custom css to the wiki (especially for [this](https://www.zigbee2mqtt.io/information/supported_devices.html) page), so all the tables have the same size (for better overview):
```css
.main-content table {
  display: table !important;
}
.main-content table tr td:first-child, 
.main-content table tr td:last-child {
  width: 25%;
}
.main-content table tr td:nth-child(2) {
  width: 50%;
}
```

Usually I would just open a PR, but I don't have any clue about jekyll and couldn't figure out, how to add own css. So I leave the code here, would be nice if you could add it
